---
title: "datacamp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(plotly)
data()
```

```{r multi/log reg}
data <- as.tibble(USPersonalExpenditure) %>% 
  mutate(total = sum(`1940`, `1945`, `1950`, `1955`, `1960`))

# 3D scatterplot
plot_ly(data = data, z = ~total, x = ~`1940`, y = ~`1960`, opacity = 0.6) %>%
  add_markers()

# fit log model
glm(Acceptance ~ GPA, data = MedGPA, family = binomial)

# scatterplot with jitter
data_space <- ggplot(MedGPA, aes(GPA, Acceptance)) + 
  geom_jitter(width = 0, height = 0.05, alpha = .5)

# add logistic curve
data_space +
  geom_smooth(method = "glm", se = FALSE, method.args = list(family = "binomial"))

# binned points and line
data_space <- MedGPA_binned %>%
ggplot(aes(mean_GPA, acceptance_rate)) +
geom_point() +
geom_line()

# augmented model
MedGPA_plus <- augment(mod, type.predict = "response")

# logistic model on probability scale
data_space +
  geom_line(data = MedGPA_plus, aes(GPA, .fitted), color = "red")

# compute odds for bins
MedGPA_binned <- MedGPA_binned %>%
mutate(odds = acceptance_rate/(1 - acceptance_rate))

# plot binned odds
data_space <- ggplot(MedGPA_binned, aes(mean_GPA, odds)) +
geom_point() +
geom_line()

# compute odds for observations
MedGPA_plus <- MedGPA_plus %>%
mutate(odds_hat = .fitted/(1-.fitted))

# logistic model on odds scale
data_space +
  geom_line(data = MedGPA_plus, aes(x = GPA, y = odds_hat), color = "red")

# compute log odds for bins
MedGPA_binned <- MedGPA_binned %>%
mutate(log_odds = log(acceptance_rate/(1-acceptance_rate)))

# plot binned log odds
data_space <- ggplot(MedGPA_binned, aes(mean_GPA, log_odds)) +
geom_point() +
geom_line()

# compute log odds for observations
MedGPA_plus <- MedGPA_plus %>%
mutate(log_odds_hat = log(.fitted/(1-.fitted)))

# logistic model on log odds scale
data_space +
  geom_line(data = MedGPA_plus, aes(x = GPA, y = log_odds_hat), color = "red")

# create new data frame
new_data <- data.frame(GPA = 3.51)

# make predictions
augment(mod, newdata = new_data, type.predict = "response")

# data frame with binary predictions
tidy_mod <- augment(mod, type.predict = "response") %>%
mutate(Acceptance_hat = round(.fitted))
  
# confusion matrix
tidy_mod %>%
  select(Acceptance, Acceptance_hat) %>% 
  table()
```

